Fix helm chart update
dubug variable needs to be a boolean as per this error message

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
korifi:
- debug: Invalid type. Expected: boolean, given: string
```

Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>